server:
  port: 8090 # puerto en el que se levantará el servicio
spring:
  application:
    name: content-service
  datasource:
    url: DB_URL # ubicación de la base de datos
    username: DB_USER
    password: DB_PASS # contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always # Asegura que los scripts SQL se ejecuten en cualquier entorno
  jpa:
    hibernate:
      ddl-auto: create # Cambiar a "none" en producción
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true # permite inicializar el archivo data.sql posteriormente
# eureka: -- este código nos servirá para cuando levantemos el servidor eureka
  # client:
    # service-url:
      # defaultZone: http://localhost:8761/eureka/