server:
  port: 8090 # puerto en el que se levantará el servicio
spring:
  application:
    name: content-service
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always # Asegura que los scripts SQL se ejecuten en cualquier entorno
  jpa:
    hibernate:
      ddl-auto: create # Cambiar a "none" en producción
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true # permite inicializar el archivo data.sql posteriormente